### ISSUE TITLE
CSS style in the index.html

### ISSUE THREAD

**Issue by ghassanmas** [fack2/repoQ#12]
Since you alraedy have a spearete style.css file, it's better to have the CSS contained in one file, 
Here are two examples where you have CSS code in the index.html: 

https://github.com/fack2/repoQ/blob/baeecc4a182a2e4c3cc5117111423b9ce10f9aa6/index.html#L152-L154

https://github.com/fack2/repoQ/blob/baeecc4a182a2e4c3cc5117111423b9ce10f9aa6/index.html#L17-L21

So you could easily rewrite than in the style.css file.

**Comment by sara219** [comment]
we remove it from html file and write it on css file!
